### ISSUE TITLE
Error deploying with compose. 

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher-compose#33] opened 2015-06-30 12:59 UTC
I can manually deploy with "Services" no problem. I then export the configs (ymls). I rebuild the cluster and use rancher compose to deploy and I get a ton of container creation errors like : 

 Message : 1bb798b6-69e4-47b3-9b04-aaa17465f6ac : Image [clemenko/demo_app1:latest] failed to pull : Error pulling image (latest) from clemenko/demo_app1, Driver overlay failed to create image rootfs 87de57de6955d5e098c7ae30ce27368be101a109d03dacabce20608e17808985: lstat /var/lib/docker/overlay/bf84c1d84a8fbea92675f0e8ff61d5b7f484462c4c44fd59f0fdda8093620024: no such file or directory 

I am using Google Compute Engine, coreos, docker 1.6.2, rancher v0.25-rc2.
My scripts are located at : https://github.com/clemenko/rancher_deploy
Specifically gce.sh

**Comment by deniseschannon** [comment] 2015-07-07 16:26
Could you provide the docker-compose.yml, rancher-compose.yml and the commmand that you ran? I haven't been able to reproduce.

Also, could you try running it with debug on? `--debug` and paste the full results?

**Comment by clemenko** [comment] 2015-07-07 16:43
Script that I ran on a Mac : 
server=104.197.49.241
api_string=$(curl -s 'http://'$server':8080/v1/apikey?projectId=1a5' -X POST -H 'Accept: application/json' --data {"type":"apikey"})

  access_key=$(echo $api_string|sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g'|grep publicValue|awk -F"|" '{print $2}')

  secret_key=$(echo $api_string|sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g'|grep secretValue|awk -F"|" '{print $2}')
 
 ./rancher-compose --url http://$server:8080/v1/projects/1a5 --access-key $access_key --secret-key $secret_key --debug --project-name Default up

scripts and ymls : https://github.com/clemenko/rancher_deploy

Nothing new outputs from rancher compose.
I am seeing the same errors.
I can build the services correctly individually. 

Actually it appears that using rancher-compose it is failing to deploy to the first two rancher-agents. 
![screen shot 2015-07-07 at 12 39 05 pm](https://cloud.githubusercontent.com/assets/3177276/8551584/91dcbc24-24a5-11e5-803a-1a8b4380ab10.jpg)

![screen shot 2015-07-07 at 12 42 09 pm](https://cloud.githubusercontent.com/assets/3177276/8551592/9eb57076-24a5-11e5-8341-d62220a0ac68.jpg)
I will leave the environment up at : http://104.197.49.241:8080

**Comment by deniseschannon** [comment] 2015-07-07 17:01
Can you try logging into one of those hosts (that are having the error) to see if you can do a docker pull of the image?

**Comment by clemenko** [comment] 2015-07-07 17:06
6612f074f2ff: Error pulling image (latest) from clemenko/demo_app1, Driver overlay failed to create image rootfs 87de57de6955d5e098c7ae30ce27368be101a109d03dacabce20608e17808985: lstat /var/lib/docker/overlay/bf84c1d84a8fbea92675f0e8ff61d5b7f484462c4c44fd59f0fdda8093620024: no such file or directory f0fdda8093620024: no such file or directory mplete 
FATA[0005] Error pulling image (latest) from clemenko/demo_app1, Driver overlay failed to create image rootfs 87de57de6955d5e098c7ae30ce27368be101a109d03dacabce20608e17808985: lstat /var/lib/docker/overlay/bf84c1d84a8fbea92675f0e8ff61d5b7f484462c4c44fd59f0fdda8093620024: no such file or directory

**Comment by deniseschannon** [comment] 2015-07-07 17:11
If you can't do a `docker pull` on the host, then it looks like there is something wrong with the host (outside of Rancher). Maybe Docker related?

Rancher appears to be working fine in the sense that it will try to deploy on all the hosts, it will eventually find the hosts that are working and deploy the number of containers in the service.

**Comment by clemenko** [comment] 2015-07-07 17:18
Does Rancher Compose write anything to /var/lib/docker/tmp? That was full on the first two servers.

**Comment by deniseschannon** [comment] 2015-07-07 17:21
Not that I could tell, but I'd have to defer to @ibuildthecloud for the correct answer.

**Comment by clemenko** [comment] 2015-07-07 17:42
I run my build script. Run docker pull on the nodes and it works ok. When I don't pre-pull the images it fails ONLY on the first two nodes. I will investigate more.

**Comment by deniseschannon** [comment] 2015-07-07 17:54
I spoke with @ibuildthecloud. Docker uses `/var/lib/docker/tmp`, but Rancher does not. Unfortunately, I won't be able to help with the docker issue. :)

**Comment by clemenko** [comment] 2015-07-07 17:56
Odd that native docker commands work. Even the rancher GUI works. But rancher compose causes this error. It looks like /var/lib/docker/tmp may not be a problem. It becomes a problem from all the failed pulls.

**Comment by deniseschannon** [comment] 2015-07-07 18:01
Doing a `docker run` on the same host doesn't have an issue?

**Comment by clemenko** [comment] 2015-07-07 18:01
Nope. The errors only show up when running rancher-compose.

**Comment by clemenko** [comment] 2015-07-08 11:57
I have confirmed the error shows up on BOTH CoreOS and CentOS. I have more testing.

**Comment by clemenko** [comment] 2015-07-08 12:12
The latest test is to build 4 agent nodes. Usually the error shows up on the first two nodes. I successfully ran docker pull on the first node. I am still seeing the error on the second node. I am testing again to see if it is isolated to the host "1h1", 1h2, 1h3 naming.

**Comment by clemenko** [comment] 2015-07-08 12:18
rebuilt, 1h2, and 1h3 were the errored servers.

**Comment by clemenko** [comment] 2015-07-08 13:20
My work around is to run docker pull before the rancher compose command. NO issues now. Check out my github repo/scripts.

**Comment by deniseschannon** [comment] 2015-07-16 04:30
@clemenko We just released a beta version of rancher-compose. I know how much you like bleeding edge. :) I still don't understand why you wouldn't be able to do a docker pull on the images on the 2 agents, but if it's happening again, please re-open.

**Comment by clemenko** [comment] 2015-07-17 11:36
Error still exists. I even created brand new docker-compose.yml and rancher-compose.yml

**Comment by deniseschannon** [comment] 2015-07-17 20:29
@clemenko Could you try with ubuntu instead of CoreOS? Also, not sure if you'd want to try Docker 1.7.1 that just came out.

**Comment by clemenko** [comment] 2015-07-18 12:18
I tested with an ubuntu box for rancher-compose and ubuntu hosts and got the same issue. 
![screen shot 2015-07-18 at 8 16 36 am](https://cloud.githubusercontent.com/assets/3177276/8761562/8804286c-2d25-11e5-9837-81d57b67a0bd.jpg)
![screen shot 2015-07-18 at 8 16 42 am](https://cloud.githubusercontent.com/assets/3177276/8761563/880e643a-2d25-11e5-923f-f6adfe71708a.jpg)


here is my docker-compose : app2:
  tty: true
  image: clemenko/demo_app2
  links:
  - redis:redis
  stdin_open: true
app1:
  tty: true
  image: clemenko/demo_app1
  links:
  - redis:redis
  stdin_open: true
redis:
  restart: 'no'
  tty: true
  image: redis
  stdin_open: true
lb1:
  ports:
  - '80'
  tty: true
  image: rancher/load-balancer-service
  links:
  - app1:app1
  stdin_open: true

rancher-compose : 
app2:
  scale: 4
app1:
  scale: 4
redis:
  scale: 1
lb1:
  scale: 4
  load_balancer_config:
    name: lb1 config

**Comment by clemenko** [comment] 2015-07-20 18:08
I have seen similar errors with smaller images (nginx/httpd) : 

app2:
  tty: true
  image: nginx
  links:
  - redis:redis
  stdin_open: true
app1:
  tty: true
  image: httpd
  links:
  - redis:redis
  stdin_open: true
redis:
  restart: 'no'
  tty: true
  image: redis
  stdin_open: true
lb:
  ports:
  - '80'
  tty: true
  image: rancher/load-balancer-service
  links:
  - app1:app1
  stdin_open: true

![screen shot 2015-07-20 at 2 07 37 pm](https://cloud.githubusercontent.com/assets/3177276/8783262/b274d906-2ee8-11e5-888c-c3e3db04d949.jpg)

**Comment by ibuildthecloud** [comment] 2015-07-21 17:08
All these errors seem like odd Docker errors with graphdrivers.  Are you sure the exact same `docker pull` command works on these servers?

**Comment by clemenko** [comment] 2015-07-21 17:12
Yup it works. Check out the function "demo"  I am using to curl the api for the keys and rancher-compose command. https://github.com/clemenko/rancher_deploy/blob/master/gce_core_rancher.sh
With the docker pull command it runs every time. Without it fails randomly.

**Comment by deniseschannon** [comment] 2015-09-23 17:45
@clemenko I am planning on closing the issues in this repo to consolidate into the rancher repo. I know there is a lot of history in this issue, but once I close the issues, it won't be visible. I believe this is a random docker issue with pulling issues. I don't believe it's a rancher-compose issue. If you still have issues, please open up in rancher.

**Closed by deniseschannon** 2015-09-23 17:45 UTC
Labels: question
